dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
- python setup.py install
script: pytest
before_install:
- openssl aes-256-cbc -K $encrypted_f1cee75f37b0_key -iv $encrypted_f1cee75f37b0_iv
  -in deploy_rsa.enc -out deploy_rsa -d
